### ISSUE TITLE
HTTPS doesn't work

### ISSUE THREAD

**Issue by jackmaninov** [x0l/show-rss-agent#5]
I agree switching to providing a feed URL makes sense. Unfortunately urllib2 doesn't support the SSL handshake on https://showrss.info if you provide an https feed URL. Error is:

`urllib2.URLError: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>`

Workaround is to only use http links for now.

**Comment by 0x0L** [comment]
Replace `https` by `http` in the input at the install
Commit 6640f0e

**Comment by 0x0L** [comment]
Thanks for reporting. Feel free to close
